{% set name = "byexample" %}
{% set version = "9.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b244832e07b0e8be84ae43749157fa98c058f40c5926382af51a938ff5eb527

build:
  # https://github.com/byexamples/byexample/issues/90; once this is fixed, this should be made noarch: python
  skip: True  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - byexample = byexample.byexample:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    # requirements from setup.py
    - pexpect 4.*
    - appdirs >=1.4.3,<2
    - pyte 0.8.0
    # optional requirements from setup.py
    - tqdm 4.*
    - pygments 2.*

test:
  commands:
    - byexample --version

about:
  home: http://github.com/byexamples/byexample
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Mix ordinary text and snippets of code in the same file and execute them as regression tests'
  description: |
    byexample is a literate programming engine where you mix ordinary text and
    snippets of code in the same file and then you execute them as regression
    tests.
    It lets you to execute the examples written in Python, Ruby or whatever in
    your documentation and validate them.
    You can always be sure that the examples are correct and your documentation
    is up to date!
  doc_url: https://byexamples.github.io/byexample/
  dev_url: https://github.com/byexamples/byexample

extra:
  recipe-maintainers:
    - saraedum
